---
- name: Configure LIMS transfer service
  hosts: all
  remote_user: sysadmin
  become: true

  tasks:
  - name: Deploy ClientFileTransfer archive
    ansible.builtin.unarchive:
      src: files/lims/ClientFileTransfer.tar.gz
      dest: /opt

  - name: Deploy ClientFileTransfer script with java config
    ansible.builtin.copy:
      src: files/lims/ClientFileTransfer
      dest: /opt/ClientFileTransfer/ClientFileTransfer
      owner: root
      group: prom
      mode: '0550'

  - name: Deploy client_file_transfer.properties
    ansible.builtin.copy:
      src: files/lims/client_file_transfer.properties
      dest: /opt/ClientFileTransfer/conf/client_file_transfer.properties
      owner: root
      group: prom
      mode: '0440'

  - name: Deploy clientfiletransfer.service
    ansible.builtin.copy:
      src: files/lims/clientfiletransfer.service
      dest: /etc/systemd/system/clientfiletransfer.service
      owner: root
      group: root
      mode: '0444'

  - name: Systemd daemon-reload
    ansible.builtin.systemd:
      daemon_reload: true

  - name: Create lims_reports directory
    ansible.builtin.file:
      path: /data/lims_reports
      state: directory
      owner: prom
      group: prom
      mode: '0755'

  - name: Create lims_reports_success directory
    ansible.builtin.file:
      path: /data/lims_reports_success
      state: directory
      owner: prom
      group: prom
      mode: '0755'

  - name: Create lims_reports_failure directory
    ansible.builtin.file:
      path: /data/lims_reports_failure
      state: directory
      owner: prom
      group: prom
      mode: '0755'

  - name: Enable clientfiletransfer.service
    ansible.builtin.systemd:
      name: clientfiletransfer
      state: started
      enabled: true
