---
- name: Configure offload reports rsyncer
  hosts: all
  remote_user: sysadmin
  become: true

  tasks:
  - name: Deploy reports rsyncer
    ansible.builtin.copy:
      src: ../ont_reports/ont_rsync_reports.py
      dest: /usr/local/bin/ont_rsync_reports
      owner: root
      group: prom
      mode: '0550'

  - name: Configure reports rsyncer
    ansible.builtin.copy:
      src: files/offload/ont_rsync_reports.yaml
      dest: /etc/ont_rsync_reports.yaml
      owner: root
      group: prom
      mode: '0440'

  - name: Install python psutil
    ansible.builtin.apt:
      name: python3-psutil
      state: present

  - name: Create reports rsyncer cron job
    ansible.builtin.cron:
      name: ont_rsync_reports
      user: prom
      minute: "{{ 60 | random(seed=inventory_hostname) }}"
      hour: "*"
      job: /usr/local/bin/ont_rsync_reports
